name: aarohan_app
description: Annual techno-management fest of NIT Durgapur.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 4.5.0+15

environment:
  sdk: ">=3.0.0 <=4.3.0"

dependencies:
  cloud_firestore: ^5.6.5
  firebase_auth: ^5.5.1
  firebase_database: ^11.3.4
  firebase_core: ^3.12.1
  google_sign_in: ^6.3.0
  provider: ^6.0.2
  flutter_signin_button: ^2.0.0
  sizer: ^2.0.15
  cached_network_image: ^3.2.3
  flutter_inappwebview: ^6.1.5
  share_plus: ^10.1.4
  url_launcher: ^6.1.12
  timeago: ^3.3.0
  barcode_scan2: ^4.5.0
  flutter_dotenv: ^5.2.1
  carousel_slider: ^5.0.0
  from_css_color: ^2.0.0
  photo_view: ^0.14.0
  google_maps_flutter: ^2.2.3 
  shared_preferences: ^2.5.2
  permission_handler: ^11.4.0
  http: ^0.13.5
  firebase_messaging: ^15.2.4
  flutter_local_notifications: ^18.0.1
  geolocator: ^13.0.2
  flame: ^1.6.0
  flame_audio: ^2.10.7
  hive: ^2.2.3
  hive_generator: ^2.0.1
  path_provider: ^2.0.11
  
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.2
  hive_flutter: ^1.1.0
  outline_gradient_button: ^2.0.1+1
  flame_noise: ^0.3.0+1

dev_dependencies:
  flutter_launcher_icons: ^0.13.1

flutter_icons:
    android: "launcher_icon"
    image_path: "assets/aarohan-logo-new.png"
flutter_test:
    sdk: flutter



flutter:


  uses-material-design: true

  assets:
    - assets/
    - assets/audio/
    - assets/fonts/
    - assets/images/




  fonts:
    - family: Bayon
      fonts:
         - asset: fonts/Bayon-Regular.ttf
    - family: AllertaStencil
      fonts:
         - asset: fonts/AllertaStencil-Regular.ttf
    - family: UrbanJungle
      fonts:
         - asset: fonts/UrbanJungleDEMO.otf
    - family: Mons
      fonts:
         - asset: fonts/Mons Olympia.otf
    - family: Staat
      fonts:
         - asset: fonts/Staatliches-Regular.ttf
    - family: Gugi
      fonts:
         - asset: fonts/Gugi-Regular.ttf
    - family: Poppins
      fonts:
         - asset: fonts/Poppins-Regular.ttf
    - family: Bebas
      fonts:
         - asset: fonts/BebasNeue-Regular.ttf
    - family: Gotham
      fonts:
        - asset: fonts/Gotham-Black.otf
    - family: Glitch
      fonts:
        - asset: fonts/GLITCH.otf
    - family: Bebas
      fonts:
        - asset: fonts/BebasNeue-Regular.ttf

    - family: Montserrat
      fonts:
         - asset: fonts/Montserrat-Regular.ttf
         - asset: fonts/Montserrat-Bold.ttf
           weight: 900
    - family: LemonMilk
      fonts:
       - asset: fonts/LEMONMILK-Bold.otf

    - family: Norwester
      fonts:
        - asset: fonts/Norwester.otf
    - family: Audiowide
      fonts:
        - asset: fonts/Audiowide.ttf
    - family: Orbitron
      fonts:
        - asset: fonts/Orbitron-VariableFont_wght.ttf
        - asset: fonts/Orbitron-Bold.ttf
          weight: 500



